package api

func (s *Server) routes() {
	s.mux.HandleFunc("GET /healthz", s.healthz)
	s.mux.HandleFunc("GET /readyz", s.readyz)
	s.mux.HandleFunc("POST /v1/buoys", s.createBuoy)
	s.mux.HandleFunc("GET /v1/buoys", s.listBuoys)
	s.mux.HandleFunc("GET /v1/buoys/{id}", s.getBuoy)
	s.mux.HandleFunc("PATCH /v1/buoys/{id}", s.patchBuoy)
	s.mux.HandleFunc("POST /v1/tasks", s.createTask)
	s.mux.HandleFunc("GET /v1/tasks", s.listTasks)
	s.mux.HandleFunc("GET /v1/tasks/{id}", s.getTask)
	s.mux.HandleFunc("GET /v1/tasks/{id}/live", s.liveTask)
	s.mux.HandleFunc("POST /v1/tasks/{id}/transitions", s.transitionTask)
	s.mux.HandleFunc("POST /v1/tasks/{id}/snapshots", s.createSnapshot)
	s.mux.HandleFunc("POST /v1/tasks/{id}/sector-sets", s.generateSectorSet)
	s.mux.HandleFunc("POST /v1/tasks/{id}/schedule-plans:auto", s.generateSchedulePlan)
	s.mux.HandleFunc("POST /v1/schedule-plans/{id}/confirm", s.confirmSchedulePlan)
	s.mux.HandleFunc("POST /v1/schedule-plans/{id}/reject", s.rejectSchedulePlan)
	s.mux.HandleFunc("POST /v1/vessels", s.createVessel)
	s.mux.HandleFunc("GET /v1/vessels", s.listVessels)
	s.mux.HandleFunc("POST /v1/vessels/{id}/heartbeats", s.heartbeatVessel)
	s.mux.HandleFunc("GET /v1/tasks/{id}/events", s.listEvents)
	s.mux.HandleFunc("GET /v1/tasks/{id}/review", s.reviewTask)
	s.mux.HandleFunc("GET /v1/notifications", s.listNotifications)
	s.mux.HandleFunc("POST /v1/notifications/{id}/read", s.readNotification)
	s.mux.HandleFunc("POST /v1/notifications/{id}/resolve", s.resolveNotification)
	s.mux.HandleFunc("GET /v1/statistics/coverage", s.coverageStatistic)
	s.mux.HandleFunc("GET /v1/statistics/vessel-utilization", s.vesselUtilizationStatistic)
	s.mux.HandleFunc("GET /v1/statistics/response-time", s.responseTimeStatistic)
	s.mux.HandleFunc("GET /v1/statistics/termination-reasons", s.terminationReasonsStatistic)
	s.mux.HandleFunc("POST /v1/assignments/{id}/claim", s.claimAssignment)
	s.mux.HandleFunc("POST /v1/assignments/{id}/progress", s.reportProgress)
}
